<?php
$que=array(
    "1"=>"<p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Stringoholics</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:white;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>You are given an array <strong>A</strong> consisting of strings made up of the letters ‘a’ and ‘b’ only.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Each string goes through a number of operations, where:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1.&nbsp;&nbsp;At time 1, you circularly rotate each string by 1 letter.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>2.&nbsp;&nbsp;At time 2, you circularly rotate the new rotated strings by 2 letters.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>3.&nbsp;&nbsp;At time 3, you circularly rotate the new rotated strings by 3 letters.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>4.&nbsp;&nbsp;At time i, you circularly rotate the new rotated strings by i % length(string) letters.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Eg: String is abaa</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1.&nbsp;&nbsp;At time 1, string is baaa, as 1 letter is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>2.&nbsp;&nbsp;At time 2, string is aaba, as 2 letters of the string baaa is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>3.&nbsp;&nbsp;At time 3, string is aaab, as 3 letters of the string aaba is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>4.&nbsp;&nbsp;At time 4, string is again aaab, as 4 letters of the string aaab is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>5.&nbsp;&nbsp;At time 5, string is aaba, as 1 letters of the string aaab is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>After some units of time, a string becomes equal to it’s original self.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Once a string becomes equal to itself, it’s letters start to rotate from the first letter again (<strong>process resets</strong>). So, if a string takes <strong>t</strong> time to get back to the original, at time t+1 one letter will be rotated and the string will be it’s original self at 2<strong>t</strong> time.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>You have to find the minimum time, where maximum number of strings are equal to their original self.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>As this time can be very large, give the answer modulo 109+7.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Note:</span></strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>&nbsp;Your solution will run on multiple test cases so do clear global variables after using them.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Input:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>A: Array of strings.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Output:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Minimum time, where maximum number of strings are equal to their original self.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Constraints:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1 &lt;= size(A) &lt;= 10^5</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1 &lt;= size of each string in A &lt;= 10^5</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Each string consists of only characters 'a' and 'b'</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Summation of length of all strings &lt;= 10^7</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Example:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Input</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>A: [a,ababa,aba]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Output</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>4</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>String 'a' is it's original self at time 1, 2, 3 and 4.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>String 'ababa' is it's original self only at time 4. (ababa =&gt; babaa =&gt; baaba =&gt; babaa =&gt; ababa)</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>String 'aba' is it's original self at time 2 and 4. (aba =&gt; baa =&gt; aba)</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Hence, 3 strings are their original self at time 4.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>TEST CASE : A : [ abc, abcd, abcde, code, luck, good, tech ]</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></strong></p>",

    "2"=>"<p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Minimum Characters required to make a String Palindromic</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:white;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Given an string <strong>A</strong>. The only operation allowed is to insert characters in the beginning of the string.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Find how many minimum characters are needed to be inserted to make the string a palindrome string.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:white;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:white;>&nbsp; &nbsp; &nbsp;&nbsp;</span><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Input Format</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>The only argument given is string A.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Output Format</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Return the minimum characters that are needed to be inserted to make the string a palindrome string.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>For Example</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Input 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; A = ABC</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Output 1:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; 2</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; <strong>Explanation 1:</strong></span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; Insert 'B' at beginning, string becomes: BABC.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; Insert 'C' at beginning, string becomes: CBABC.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Input 2:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; A = AACECAAAA</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Output 2:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; 2</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; <strong>Explanation 2:</strong></span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; Insert 'A' at beginning, string becomes: AAACECAAAA.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; Insert 'A' at beginning, string becomes: AAAACECAAAA.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>TEST CASE : A : aabbccddeefffghhfffeeddccbb</span></strong></p>",

 "3"=>"<p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Given a set of distinct integers, S, return all possible subsets.</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#7F7F7F;>Note:</span></p>
 <ul>
   <li>Elements in a subset must be in non-descending order.</li>
   <li>The solution set must not contain duplicate subsets.</li>
   <li>Also, the subsets should be sorted in ascending ( lexicographic ) order.</li>
   <li>The list is not necessarily sorted.</li>
 </ul>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>&nbsp;</span></strong></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Example :</span></strong></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>If&nbsp;</span>S = [1,2,3],<span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>&nbsp;a solution is:</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>[</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [1],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [1, 2],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [1, 2, 3],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [1, 3],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [2],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [2, 3],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; [3],</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>]</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
 <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>TEST CASE : [ 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]</span></strong></p>",


 "4"=>"<p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Stringoholics</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:white;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>You are given an array <strong>A</strong> consisting of strings made up of the letters ‘a’ and ‘b’ only.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Each string goes through a number of operations, where:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1.&nbsp;&nbsp;At time 1, you circularly rotate each string by 1 letter.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>2.&nbsp;&nbsp;At time 2, you circularly rotate the new rotated strings by 2 letters.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>3.&nbsp;&nbsp;At time 3, you circularly rotate the new rotated strings by 3 letters.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>4.&nbsp;&nbsp;At time i, you circularly rotate the new rotated strings by i % length(string) letters.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Eg: String is abaa</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1.&nbsp;&nbsp;At time 1, string is baaa, as 1 letter is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>2.&nbsp;&nbsp;At time 2, string is aaba, as 2 letters of the string baaa is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>3.&nbsp;&nbsp;At time 3, string is aaab, as 3 letters of the string aaba is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>4.&nbsp;&nbsp;At time 4, string is again aaab, as 4 letters of the string aaab is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>5.&nbsp;&nbsp;At time 5, string is aaba, as 1 letters of the string aaab is circularly rotated to the back</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>After some units of time, a string becomes equal to it’s original self.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Once a string becomes equal to itself, it’s letters start to rotate from the first letter again (<strong>process resets</strong>). So, if a string takes <strong>t</strong> time to get back to the original, at time t+1 one letter will be rotated and the string will be it’s original self at 2<strong>t</strong> time.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>You have to find the minimum time, where maximum number of strings are equal to their original self.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>As this time can be very large, give the answer modulo 109+7.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Note:</span></strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>&nbsp;Your solution will run on multiple test cases so do clear global variables after using them.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Input:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>A: Array of strings.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Output:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Minimum time, where maximum number of strings are equal to their original self.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Constraints:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1 &lt;= size(A) &lt;= 10^5</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1 &lt;= size of each string in A &lt;= 10^5</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Each string consists of only characters 'a' and 'b'</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Summation of length of all strings &lt;= 10^7</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Example:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Input</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>A: [a,ababa,aba]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Output</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>4</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>String 'a' is it's original self at time 1, 2, 3 and 4.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>String 'ababa' is it's original self only at time 4. (ababa =&gt; babaa =&gt; baaba =&gt; babaa =&gt; ababa)</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>String 'aba' is it's original self at time 2 and 4. (aba =&gt; baa =&gt; aba)</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Hence, 3 strings are their original self at time 4.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>TEST CASE : A : [ abc, abcd, abcde, code, luck, good, tech ]</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:22.5pt;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></strong></p>"
);

?>