<?php
$que1 = array(
    "1"=>"<p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;>Given two integer arrays <strong>A</strong> and <strong>B</strong> of size <strong>N</strong>.&nbsp;</span><span style=background:#F8F8F8;>There are <strong>N</strong> gas stations along a circular route, where the amount of gas at station <strong>i</strong> is <strong>A[i]</strong>.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>You have a car with an unlimited gas tank and it costs <strong>B[i]</strong> of gas to travel from station <strong>i</strong>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>to its next station <strong>(i+1)</strong>. You begin the journey with an empty tank at one of the gas stations.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>Return the minimum starting gas station’s index if you can travel around the circuit once, otherwise return -1.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>You can only travel in one direction. <strong>i to i+1, i+2, … n-1, 0, 1, 2..</strong> Completing the circuit means starting at <strong>i</strong> and&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>ending up at <strong>i</strong> again.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F8F8F8;>Input Format</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>The first argument given is the integer array A.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>The second argument given is the integer array B.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F8F8F8;>Output Format</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>Return the minimum starting gas station's index if you can travel around the circuit once, otherwise return -1.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F8F8F8;>For Example</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>Input 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; A = &nbsp; [1, 2]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; B = &nbsp; [2, 1]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>Output 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; 1</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; Explanation 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; If you start from index 0, you can fill in A[0] = 1 amount of gas. Now your tank has 1 unit of gas. But you need B[0] = 2 gas to travel to station 1.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; If you start from index 1, you can fill in A[1] = 2 amount of gas. Now your tank has 2 units of gas. You need B[1] = 1 gas to get to station 0. So, you travel to station 0 and still have 1 unit of gas left over. You fill in A[0] = 1 unit of additional gas, making your current gas = 2. It costs you B[0] = 2 to get to station 1, which you do and complete the circuit.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F7F7F7;>TEST CASE :&nbsp;</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F7F7F7;>A : [ 3, 1, 4, 2, 5 ]</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F7F7F7;>B : [ 3, 2, 3, 2, 1 ]</span></strong></p>", 












    "2"=>"<p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;text-indent:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Given a string <strong>A</strong>, partition <strong>A</strong> such that every substring of the partition is a palindrome.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Return the <strong>minimum</strong> cuts needed for a palindrome partitioning of <strong>A</strong>.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Input Format:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>The first and the only argument contains the string A.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Output Format:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Return an integer, representing the answer as described in the problem statement.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Constraints:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1 &lt;= length(A) &lt;= 501</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Examples:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Input 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; A = aba</span><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Output 1:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; 0</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Explanation 1:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; aba is already a palindrome, so no cuts are needed.</span><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Input 2:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; A = aab</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Output 2:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; 1</span><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Explanation 2</span></strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; Return 1 since the palindrome partitioning [aa,b] could be produced using 1 cut.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Test Case : &nbsp; A : sfjalsdkjfassfdjal</span></strong></p>",










    "3"=>"<p style=margin-top:0in;margin-right:0in;margin-bottom:.0001pt;margin-left:.25in;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;><span style=color:#333333;background:#F7F7F7;>Find the <strong>longest increasing subsequence</strong> of a given array of integers, <strong>A</strong>.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>In other words, find a subsequence of array in which the subsequence’s elements are in strictly increasing order, and in which the subsequence is as long as possible.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>This subsequence is not necessarily contiguous, or unique.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>In this case, we only care about the <strong>length</strong> of the longest increasing subsequence.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Input Format:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>The first and the only argument is an integer array A.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Output Format:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Return an integer representing the length of the longest increasing subsequence.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Constraints:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1 &lt;= length(A) &lt;= 2500</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>1 &lt;= A[i] &lt;= 2000</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F8F8F8;>Example :</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Input 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; A = [1, 2, 1, 5]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; &nbsp;&nbsp;</span><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Output 1:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; 3</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Explanation 1:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; The sequence : [1, 2, 5]</span><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Input 2:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; A = [0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Output 2:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; 6</span><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Explanation 2:</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; The sequence : [0, 2, 6, 9, 13, 15] or [0, 4, 6, 9, 11, 15] or [0, 4, 6, 9, 13, 15]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>Test Case :</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><strong><span style=font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;color:#333333;background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; A : [ 2, 4, 6, 8, 10, 9, 7, 5, 3, 1, 11, 13, 15, 17, 19, 18, 16, 14, 12, 20 ]</span></strong></p>",





    "4"=>"<p style=margin:0in;margin-bottom:.0001pt;font-size:15px;font-family:&quot;Helvetica Neue&quot;,&quot;serif&quot;;color:black;border:none;margin-left:.25in;><span style=font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;>Given two integer arrays <strong>A</strong> and <strong>B</strong> of size <strong>N</strong>.&nbsp;</span><span style=background:#F8F8F8;>There are <strong>N</strong> gas stations along a circular route, where the amount of gas at station <strong>i</strong> is <strong>A[i]</strong>.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>You have a car with an unlimited gas tank and it costs <strong>B[i]</strong> of gas to travel from station <strong>i</strong>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>to its next station <strong>(i+1)</strong>. You begin the journey with an empty tank at one of the gas stations.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>Return the minimum starting gas station’s index if you can travel around the circuit once, otherwise return -1.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>You can only travel in one direction. <strong>i to i+1, i+2, … n-1, 0, 1, 2..</strong> Completing the circuit means starting at <strong>i</strong> and&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F8F8F8;>ending up at <strong>i</strong> again.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F8F8F8;>Input Format</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>The first argument given is the integer array A.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>The second argument given is the integer array B.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F8F8F8;>Output Format</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>Return the minimum starting gas station's index if you can travel around the circuit once, otherwise return -1.</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F8F8F8;>For Example</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>Input 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; A = &nbsp; [1, 2]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; B = &nbsp; [2, 1]</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>Output 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; 1</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; Explanation 1:</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; If you start from index 0, you can fill in A[0] = 1 amount of gas. Now your tank has 1 unit of gas. But you need B[0] = 2 gas to travel to station 1.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp; &nbsp; &nbsp; &nbsp; If you start from index 1, you can fill in A[1] = 2 amount of gas. Now your tank has 2 units of gas. You need B[1] = 1 gas to get to station 0. So, you travel to station 0 and still have 1 unit of gas left over. You fill in A[0] = 1 unit of additional gas, making your current gas = 2. It costs you B[0] = 2 to get to station 1, which you do and complete the circuit.&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><span style=background:#F7F7F7;>&nbsp;</span></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F7F7F7;>TEST CASE :&nbsp;</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F7F7F7;>A : [ 3, 1, 4, 2, 5 ]</span></strong></p>
    <p style=margin:0in;margin-bottom:.0001pt;font-size:16px;font-family:&quot;Times New Roman&quot;,&quot;serif&quot;;border:none;margin-left:.25in;><strong><span style=background:#F7F7F7;>B : [ 3, 2, 3, 2, 1 ]</span></strong></p>");


?>